# -*- coding: utf-8 -*-
"""Копия блокнота "lesson5.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bPafapxEWSX3EAF5NbSvf6sCQo_gZu8Z
"""

#Задание 1
n = int(input())
cnt = 0
my_list = [input() for i in range(n)]
unique_elem = set(my_list)
for s in unique_elem:
  if my_list.count(s) > 1:
    cnt += my_list.count(s)
print(cnt)

#Задание 2
mylist = input().split()
mylist[0] = mylist[0].capitalize()
for i in range(len(mylist) - 1):
  if mylist[i].endswith((".", "!", "?")):
    mylist[i+1] = mylist[i+1].capitalize()
print(" ".join(mylist))

#Задание 3
str1 = input().lower().replace(" ", "")
str2 = input().lower().replace(" ", "")
set1 = set(str1)
set2 = set(str2)
print(("Строки не являются анаграммами", "Строки являются анаграммами")[set1 == set2])

#Задание 4
set1 = set(input().split())
set2 = set(input().split())
set3 = set(input().split())
res_set = set1.intersection(set2, set3)
if len(res_set) == 0:
  print("Все три задачи никто не решил")
else:
  res = " ".join(sorted(res_set))
  print(res)