# -*- coding: utf-8 -*-
"""lesson7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vKZ2c2E0I29aw9ygUm-PeOop_LbnFTBj
"""

#Задание 1
list1 = [5, 3, 7, 9, 13]
list2 = [6, 8 ,1, 5, 2, 17, 12, 69]
reslist = list(map(lambda x, y: x + y, list1, list2)) + list1[len(list2):] + list2[len(list1):]
print(reslist)

#Задание2
mylist = [55, 39, 67, 38, 76, 117]
reslist = list(filter(lambda a: a % 13 == 0 or a % 19 == 0, mylist))
print(reslist)

#Задание 3
from functools import reduce
mylist = [5, 6, 11, 2, 8, 3]
# вар.1
res = reduce(max, mylist)
print(res)
# вар.2
res = reduce(lambda a, b: a if (a > b) else b, mylist)
print(res)

