# -*- coding: utf-8 -*-
"""lesson8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lNCsoGTtRKVHmx17DWXx6GxtK4F-ME6a
"""

def maximum(lst):
    if len(lst) == 1:
        return lst[0]
    b = maximum(lst[1:])
    a = lst[0]
    return a if a > b else b

lst = [5, 3, 16, 10, 0, 8]
print(maximum(lst))