# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lNbe4Ek3-qxIedxi1ggK7TvY_tHjbdpU
"""

a = input()
a = float(a)
print(round(a, 2))

a = float(input())
b = float(input())
print(round((a + b)/2))